/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/docs/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as graphql from "@nestjs/graphql";
import * as apollo from "apollo-server-express";
import * as nestAccessControl from "nest-access-control";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { CreateScanArgs } from "./CreateScanArgs";
import { UpdateScanArgs } from "./UpdateScanArgs";
import { DeleteScanArgs } from "./DeleteScanArgs";
import { ScanFindManyArgs } from "./ScanFindManyArgs";
import { ScanFindUniqueArgs } from "./ScanFindUniqueArgs";
import { Scan } from "./Scan";
import { Customer } from "../../customer/base/Customer";
import { ScanService } from "../scan.service";

@graphql.Resolver(() => Scan)
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
export class ScanResolverBase {
  constructor(
    protected readonly service: ScanService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "Scan",
    action: "read",
    possession: "any",
  })
  async _scansMeta(
    @graphql.Args() args: ScanFindManyArgs
  ): Promise<MetaQueryPayload> {
    const results = await this.service.count({
      ...args,
      skip: undefined,
      take: undefined,
    });
    return {
      count: results,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [Scan])
  @nestAccessControl.UseRoles({
    resource: "Scan",
    action: "read",
    possession: "any",
  })
  async scans(@graphql.Args() args: ScanFindManyArgs): Promise<Scan[]> {
    return this.service.findMany(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => Scan, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "Scan",
    action: "read",
    possession: "own",
  })
  async scan(@graphql.Args() args: ScanFindUniqueArgs): Promise<Scan | null> {
    const result = await this.service.findOne(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => Scan)
  @nestAccessControl.UseRoles({
    resource: "Scan",
    action: "create",
    possession: "any",
  })
  async createScan(@graphql.Args() args: CreateScanArgs): Promise<Scan> {
    return await this.service.create({
      ...args,
      data: {
        ...args.data,

        customer: args.data.customer
          ? {
              connect: args.data.customer,
            }
          : undefined,
      },
    });
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => Scan)
  @nestAccessControl.UseRoles({
    resource: "Scan",
    action: "update",
    possession: "any",
  })
  async updateScan(@graphql.Args() args: UpdateScanArgs): Promise<Scan | null> {
    try {
      return await this.service.update({
        ...args,
        data: {
          ...args.data,

          customer: args.data.customer
            ? {
                connect: args.data.customer,
              }
            : undefined,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new apollo.ApolloError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => Scan)
  @nestAccessControl.UseRoles({
    resource: "Scan",
    action: "delete",
    possession: "any",
  })
  async deleteScan(@graphql.Args() args: DeleteScanArgs): Promise<Scan | null> {
    try {
      return await this.service.delete(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new apollo.ApolloError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.ResolveField(() => Customer, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "Customer",
    action: "read",
    possession: "any",
  })
  async customer(@graphql.Parent() parent: Scan): Promise<Customer | null> {
    const result = await this.service.getCustomer(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }
}
